#index:
#    path: /
#    controller: App\Controller\DefaultController::index

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix:   /_error
